# Generated by Django 2.2.9 on 2020-01-09 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clazz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('avatar', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=30)),
                ('introduction', models.TextField()),
                ('contact_way', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.CharField(blank=True, max_length=30, null=True)),
                ('word', models.TextField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(0, '文本'), (1, 'PPT'), (2, '视频')], default=0)),
                ('state', models.IntegerField(choices=[(0, '开放'), (1, '关闭')], default=0)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Content')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('introduction', models.TextField()),
                ('location', models.CharField(max_length=30)),
                ('begin_time', models.DateField()),
                ('end_time', models.DateField()),
                ('state', models.IntegerField(choices=[(0, '已关闭'), (1, '开放中')], default=1)),
                ('clazz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clazz.Clazz')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
    ]
