# Generated by Django 2.2.9 on 2020-01-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='state',
            field=models.IntegerField(choices=[(0, '开放'), (1, '关闭')], default=1),
        ),
    ]
