# Generated by Django 2.2.9 on 2020-01-10 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200110_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='icon',
            field=models.CharField(default='https://i.loli.net/2020/01/09/iEZpONujHL4Sc13.png', max_length=1000),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.CharField(default='https://i.loli.net/2020/01/09/zkinxqPBwbtdvXQ.png', max_length=1000),
        ),
    ]
