# Generated by Django 2.2.9 on 2020-01-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_resource_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='state',
            field=models.IntegerField(default=1),
        ),
    ]
