# Generated by Django 2.2.9 on 2020-01-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_content_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='avatar',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
