# Generated by Django 2.2.9 on 2020-01-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20200110_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='sort',
        ),
        migrations.AddField(
            model_name='course',
            name='sort',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
