# Generated by Django 2.2.9 on 2019-12-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=30)),
                ('privilege_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment', models.IntegerField(choices=[(1, '已授权'), (2, '未授权')])),
                ('semester', models.IntegerField(choices=[(1, '已授权'), (2, '未授权')])),
                ('activity', models.IntegerField(choices=[(1, '已授权'), (2, '未授权')])),
                ('student', models.IntegerField(choices=[(1, '已授权'), (2, '未授权')])),
            ],
        ),
    ]
