# Generated by Django 2.2.9 on 2020-01-09 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment', models.IntegerField(choices=[(1, '已授权'), (0, '未授权')], default=0)),
                ('semester', models.IntegerField(choices=[(1, '已授权'), (0, '未授权')], default=0)),
                ('activity', models.IntegerField(choices=[(1, '已授权'), (0, '未授权')], default=0)),
                ('student', models.IntegerField(choices=[(1, '已授权'), (0, '未授权')], default=0)),
                ('super', models.IntegerField(choices=[(1, '已授权'), (0, '未授权')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=30)),
                ('state', models.IntegerField(choices=[(1, '活动'), (0, '锁定')], default=1)),
                ('privilege', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Privilege')),
            ],
        ),
    ]
