# Generated by Django 2.2.9 on 2019-12-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privilege',
            name='super',
            field=models.IntegerField(choices=[(1, '已授权'), (2, '未授权')], default=2),
        ),
    ]
