# Generated by Django 2.2.9 on 2020-01-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_privilege_super'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='state',
            field=models.IntegerField(default=1),
        ),
    ]
