# Generated by Django 2.2.9 on 2020-01-09 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('clazz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('enroll_start_time', models.DateField()),
                ('enroll_end_time', models.DateField()),
                ('organizer', models.CharField(max_length=30)),
                ('start_time', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('arrangement', models.TextField(max_length=1000)),
                ('price', models.IntegerField()),
                ('current_people_number', models.IntegerField(default=0)),
                ('people_number_limit', models.IntegerField()),
                ('state', models.IntegerField(choices=[(0, '未开始报名'), (1, '报名中'), (2, '招生结束没开始'), (3, '进行中'), (4, '已结束'), (5, '已取消')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'WAIT_FOR_PAY'), (1, 'PAID')], default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityClazz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity')),
                ('clazz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clazz.Clazz')),
            ],
        ),
    ]
