# Generated by Django 2.2.9 on 2019-12-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('enroll_start_time', models.DateField()),
                ('enroll_end_time', models.DateField()),
                ('organizer', models.CharField(max_length=30)),
                ('start_time', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('arrangement', models.TextField(max_length=1000)),
                ('price', models.FloatField()),
                ('people_number_limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityClazz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.IntegerField()),
                ('clazz_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('state', models.IntegerField(choices=[(0, 'WAIT_FOR_PAY'), (1, 'PAID')])),
            ],
        ),
    ]
