# Generated by Django 2.2.9 on 2020-01-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='icon',
            field=models.CharField(default='https://i.loli.net/2020/01/09/iEZpONujHL4Sc13.png', max_length=1000),
        ),
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.CharField(default='https://i.loli.net/2020/01/10/d5SzG6vIwA7PpkJ.png', max_length=1000),
        ),
    ]
