# Generated by Django 2.2.9 on 2020-01-09 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_application', models.TextField()),
                ('contribution_for_us', models.TextField(blank=True, null=True)),
                ('way', models.CharField(max_length=100)),
                ('accept_absence', models.IntegerField(choices=[(0, '接受'), (1, '拒绝')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('website', models.CharField(blank=True, max_length=30, null=True)),
                ('wx_public', models.CharField(blank=True, max_length=30, null=True)),
                ('create_time', models.DateField()),
                ('city', models.CharField(max_length=30)),
                ('number_employee', models.IntegerField()),
                ('position', models.CharField(max_length=30)),
                ('introduction', models.TextField()),
                ('company_data', models.TextField()),
                ('income_scale', models.CharField(max_length=30)),
                ('value_of_assessment', models.CharField(max_length=20)),
                ('financing_situation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraction', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
                ('phone_number', models.CharField(max_length=11)),
                ('wx', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('school', models.CharField(max_length=60)),
                ('previous_company', models.CharField(max_length=30)),
                ('profession', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('previous_position', models.CharField(max_length=100)),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女')], default=0)),
                ('state', models.IntegerField(choices=[(0, '不再是校友'), (1, '还未毕业的校友'), (2, '校友')], default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Company')),
            ],
        ),
        migrations.CreateModel(
            name='WechatStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=200)),
                ('open_id', models.CharField(max_length=200)),
                ('avatar_url', models.CharField(max_length=1000)),
                ('session_key', models.CharField(max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_peoples', to='student.ApplicationInformation')),
            ],
        ),
    ]
