# Generated by Django 2.2.9 on 2019-12-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_create_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='the_wx_public',
            new_name='wx_public',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='previous_school',
            new_name='previous_company',
        ),
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.IntegerField(choices=[(0, '不再是校友'), (1, '还未毕业的校友'), (2, '校友')]),
        ),
    ]
