# Generated by Django 2.2.9 on 2020-01-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wechatstudent',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='student',
            name='avatar_url',
            field=models.CharField(default='https://i.loli.net/2020/01/09/HCuBwxX5eOWsSfh.jpg', max_length=1000),
            preserve_default=False,
        ),
    ]
