# Generated by Django 2.2.9 on 2020-01-07 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_wechatstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatstudent',
            name='student',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
