# Generated by Django 2.2.9 on 2020-01-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20200109_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='income_scale',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='value_of_assessment',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='wx_public',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='wx',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
