# Generated by Django 2.2.9 on 2020-01-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20200107_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profession',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
