# Generated by Django 2.2.9 on 2020-01-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='fraction',
            field=models.IntegerField(null=True),
        ),
    ]
