# Generated by Django 2.2.9 on 2020-01-08 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20200108_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationpeople',
            name='information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_people', to='student.ApplicationInformation'),
        ),
    ]
