# Generated by Django 2.2.9 on 2019-12-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clazz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_id', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('introduction', models.TextField(max_length=1000)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('people_number_limit', models.IntegerField()),
                ('current_people_number', models.IntegerField()),
                ('state', models.IntegerField(choices=[(0, '正在报名'), (1, '进行中'), (2, '已结束')])),
            ],
        ),
        migrations.CreateModel(
            name='ClazzStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clazz_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('apply_id', models.IntegerField()),
                ('evaluation_id', models.IntegerField()),
                ('state', models.IntegerField(choices=[(0, '待审核'), (1, '已拒绝'), (2, '已通过'), (3, '已毕业'), (4, '未能完成')])),
            ],
        ),
    ]
