# Generated by Django 2.2.9 on 2020-01-09 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semester', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clazz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('introduction', models.TextField(max_length=1000)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('people_number_limit', models.IntegerField()),
                ('current_people_number', models.IntegerField(default=0)),
                ('state', models.IntegerField(choices=[(0, '没有开始招生'), (1, '招生中'), (2, '招生结束没开课'), (3, '开课中'), (4, '已结束')], default=0)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clazzes', to='semester.Semester')),
            ],
        ),
        migrations.CreateModel(
            name='ClazzStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, '待审核'), (1, '已拒绝'), (2, '已通过'), (3, '已毕业'), (4, '未能完成')], default=0)),
                ('apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.ApplicationInformation')),
                ('clazz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clazz.Clazz')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Evaluation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
